apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dbsecretname-secret-sealed
  namespace: default
spec:
  encryptedData:
    dbsecretname.txt: AgBm1b/HWyNbM0G5jTve+qEL2qABXxR6O60KIB2Y4ZnYcSdto28h/uOwv9GtosZvScHVvWAUzS2pbogfPQUemoRGiKtHaJuADgOlWT5NZDeqXxPNAvTlds493aK7eFQH+6pF6VUm06UAHNKTY4a0ew193GdbULTvd0ot54kOzjFPHeBkZeP54RH2S4KfsP/5/2XrBaBYQxpHj8VWOLY4RVr/JvFCVyj6MuflMuvbhSNB9Fa7le6fMifqc8W2KD50rQGd3Y5XL+I6TmOW/Yj3gvy66+Uq7TE2Evaf4XC/wMo/kzMI4zcuFQgk/UpN0EhlC2bSp7YsIYOBzulYGwYBeR+oempowpfaL87QF8N0uVb0i8608lnj8hRHSEuCq6OJDm75SVBXTGRLjQu/yjWm7yPXx5U2ZHDUYxbdMyPCdWti+OadrMo+J1ztsA4jj4wRUej5/D3Di73WVymAJfdfBxBrduNDSIoonSivlR+CIyzz/dnt+W7GfAR6fenJ/mlxkMoFG4JJiKIMcgcKPHmgmazOinuTT1QPA3wvRPDghf/Bai1ykwuSa9Yp5/5l5NhY99VNR9lnLMhibDcCegSR0vKO6WmT1HnTuk1YJG3xUwnlehvjr2INYPRWYGHuBF1revjNRsFIjyNEn6rlcPJ8yP79qlT3Zv6g9ffZONa/ue5/+UUc37+FM1kiqjeK9W70c6DrpuIB0gD6HA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:dbsecretname.txt: {}
          f:type: {}
        manager: kubectl-create
        operation: Update
        time: "2021-03-10T04:14:22Z"
      name: dbsecretname-secret-sealed
      namespace: default
    type: Opaque

