apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dbsecretname-secret
  namespace: default
spec:
  encryptedData:
    dbsecretname.txt: AgCHY9Q4vugEu0b3Rhl1mqt88W0bMNCoP3hsk5eVLSh4l+kTTnmbt8YWQ2u/zPjlquUW58UIuUmqdWwrLXGoaalZpo+e70piPv90HuSA708mdrgT9rEl6xX6eJhaASMDKBUyxpaa2b9ufls8vMmbCwqX1h31rloOkmjSBk9vxLTYWLO8ALAb5GiaPwXVuJN3CGFypgNLvroBRz5gKaRJKN7EcI9xWPGGaKd0AFfD0QBuyuc1IW8u7VGo6Jkd8Rbyio07kQlakyT5ulL4fKH3ZvtIVu5RWWjli38aRp3p1dg8pcd0WfmgwcZ7NPVjglmYgGDcFx74C4mTbBHHuvcaKCKki7ftMxIE4JKAeayzXbe+PyNapUuTl5ZC+/fkQjXLvGFYq0aNVUCNtKt3wjMDB6FFnHjFcdkNqazGtrQuYKV4J/vakBpgSHh7drfSWC2OXuxL3Z+G41jj/Uxc5z39NdQ7G9R+V3G8xZAgxp1qr8IlfxZDFeLbSqtEpNdaGNyLpIHNIM/02uvB+FyejxSz7du2Mm6QTdCRrGS6dRlWcspPcYOS3KyxslbQiE/UcMDMdiSwtBWzSAEIWv0WwXKODpNCawzt57W03lBwsPjzn+siQZl8/wuW4s1Fo4/nf9WlG97MImeUiYe5iqNzJe+A/YHgW04EDVlJbdV0H6cIRj7q/tJI5nFNGWT3CyyFoBrI6pIjT4noGu5DWw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:dbsecretname.txt: {}
          f:type: {}
        manager: kubectl-create
        operation: Update
        time: "2021-03-10T03:49:26Z"
      name: dbsecretname-secret
      namespace: default
    type: Opaque

